<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Produit;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllCategories(){
        $em = $this ->getEntityManager();
        $query = $em -> createQueryBuilder();
        $query
            ->select('p.categorie')
            ->distinct(true)
            ->from(produit::class,'p')
            ->orderBy('p.categorie','ASC');

        //SELECT DISTINCT(categorie) FROM produit ORDER BY categorie ASC
        return $query ->getQuery()-> getResult();
    }



    public function getAllCategories2(){
        $em = $this ->getEntityManager();
        $query=createQuery("SELECT DISTINCT(p.categorie) FROM AppBundle\Entity\Produit ORDER BY p.categorie ASC");
        return $query -> getResult();
    }
}
